name: wander_ways
version: 1.0.0+1
publish_to: none
description: Flutter Booking App project for recruitment process held by PT
  Implementasi Teknologi Digital.
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  dio: ^5.4.1
  dropdown_button2: ^2.3.9
  email_validator: ^2.1.17
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.10+1
  flutter_switch: ^0.3.2
  freezed_annotation: ^2.4.1
  get: 4.6.6
  intl: ^0.18.1
  json_annotation: ^4.8.1
  loading_animation_widget: ^1.2.1
  path: ^1.9.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.2
  syncfusion_flutter_datepicker: ^25.1.35

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: false
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/NunitoSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/NunitoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/NunitoSans-BoldItalic.ttf
          weight: 700
          style: italic
