name: wander_ways
version: 1.0.0+1
publish_to: none
description: Flutter Booking App project for recruitment process held by PT
  Implementasi Teknologi Digital.
environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.10+1
  get: 4.6.6

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/NunitoSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/NunitoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/NunitoSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/NunitoSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/NunitoSans-BoldItalic.ttf
          weight: 700
          style: italic
